"use client";

import type { CountryData } from "@/lib/types";

const SOURCES = [
  "GDELT (2 min ago)",
  "ACLED (3 days ago)",
  "UCDP (2024)",
  "World Bank (2024)",
  "NewsAPI (live)",
];

type Props = { country: CountryData };

export function MLTransparency({ country }: Props) {
  const confidence = (country.confidence * 100).toFixed(1);
  return (
    <section className="space-y-2">
      <h2 className="text-sm font-semibold uppercase text-muted-foreground">ML Transparency</h2>
      <div className="space-y-2">
        {country.featureImportance.slice(0, 10).map((f) => (
          <div key={f.name} className="space-y-1">
            <div className="flex justify-between text-xs">
              <span className="truncate">{f.name}</span>
              <span>{f.percentage}%</span>
            </div>
            <div className="h-2 rounded-full bg-muted overflow-hidden">
              <div className="h-full bg-primary rounded-full" style={{ width: `${f.percentage}%` }} />
            </div>
          </div>
        ))}
      </div>
      <p className="text-xs font-medium">Model Confidence: {confidence}%</p>
      <div className="flex flex-wrap gap-1">
        {SOURCES.map((s) => (
          <span key={s} className="text-[10px] px-1.5 py-0.5 rounded bg-muted">{s}</span>
        ))}
      </div>
      <p className="text-xs text-muted-foreground">
        This assessment is generated by a 47-feature XGBoost model trained on 75 years of conflict data. The intelligence brief is produced by GPT-4o explaining the ML output.
      </p>
    </section>
  );
}
